apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: HELLO
          value: WORLD
        image: |
          quay.io/redhat-appstudio/sample-image@sha256:7e617933097884285054b322c76d243d4a210695dcbfcaa83da337f15bac3b7e
        name: container-image
        resources: {}
status: {}
