apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: HELLO
          value: WORLD
        - name: KUBEC
          value: ~/.kube/conf
        image: |
          quay.io/redhat-appstudio/sample-image@sha256:0c921bbabc0503bc23abfa92b5a4dab3c14f362b16096238fb4a71c279bc0eeb
        name: container-image
        resources: {}
status: {}
