apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: UNKNOWN
          value: KNOWN
        - name: HELLO
          value: WORLD
        image: |
          quay.io/redhat-appstudio/sample-image@sha256:236a9bec7f8edb54c90d41be2953f82f774eba8b5be4eff1ba1df131d95f9b50
        name: container-image
        resources: {}
status: {}
