apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample
    app.kubernetes.io/part-of: example-application
  name: component-sample
  namespace: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:integration-service-component-sample
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
